In [2]:
import numpy as np 

In [1]:
p=[7,8,9,90]

In [3]:
np.asarray(p)

array([ 7,  8,  9, 90])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,5))


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [10]:
np.empty((5,4,2))

array([[[ 1.27946415e-307, -4.34719909e-311],
        [ 3.22649121e-307,  4.00536043e-307],
        [ 3.56036263e-307,  3.56044072e-307],
        [ 6.89796323e-307,  2.33645827e-307]],

       [[ 8.34441742e-308,  1.42418987e-306],
        [ 1.60218763e-306,  1.42418851e-306],
        [ 1.05699072e-307,  6.89791910e-307],
        [ 2.78148832e-307,  4.45044310e-307]],

       [[ 4.89546806e-307, -5.07292191e-311],
        [ 3.22649121e-307,  3.56038300e-307],
        [ 4.00537401e-307,  2.78146116e-307],
        [ 1.61324900e-307,  3.56043053e-307]],

       [[ 1.60219306e-306,  2.44763557e-307],
        [ 1.69119330e-306,  1.29061821e-306],
        [ 4.45061456e-308,  9.34604358e-307],
        [ 3.44897822e-307,  3.33774490e-307]],

       [[ 2.55896905e-307, -5.59705409e-311],
        [ 4.22787460e-307,  1.22383816e-307],
        [ 1.44635488e-307,  1.37962320e-306],
        [ 1.29060871e-306,  1.24611266e-306]]])

In [12]:
np.linspace(3,7,100,endpoint=False,retstep=True)

(array([3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28, 3.32, 3.36, 3.4 ,
        3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72, 3.76, 3.8 , 3.84,
        3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16, 4.2 , 4.24, 4.28,
        4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 , 4.64, 4.68, 4.72,
        4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04, 5.08, 5.12, 5.16,
        5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48, 5.52, 5.56, 5.6 ,
        5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92, 5.96, 6.  , 6.04,
        6.08, 6.12, 6.16, 6.2 , 6.24, 6.28, 6.32, 6.36, 6.4 , 6.44, 6.48,
        6.52, 6.56, 6.6 , 6.64, 6.68, 6.72, 6.76, 6.8 , 6.84, 6.88, 6.92,
        6.96]),
 np.float64(0.04))

In [13]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [14]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [17]:
a = np.arange(2,20).reshape(6,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [18]:
a.max(axis = 0)

array([17, 18, 19])

In [19]:
a.max(axis = 1)

array([ 4,  7, 10, 13, 16, 19])

In [20]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [21]:
10+ a

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [22]:
a/0

C:\Users\selfk\AppData\Local\Temp\ipykernel_7808\4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [23]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [24]:
a**3

array([[   8,   27,   64],
       [ 125,  216,  343],
       [ 512,  729, 1000],
       [1331, 1728, 2197],
       [2744, 3375, 4096],
       [4913, 5832, 6859]])

In [25]:
pow(a,3)

array([[   8,   27,   64],
       [ 125,  216,  343],
       [ 512,  729, 1000],
       [1331, 1728, 2197],
       [2744, 3375, 4096],
       [4913, 5832, 6859]])

In [26]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [35]:
b = np.arange(6,24).reshape(6,3)

In [36]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42]])

In [39]:
b = b.reshape(-1664566,1)
b.reshape(6,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [41]:
b.T

array([[ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23]])

In [42]:
a + 10

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [43]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128],
       [3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894]])

In [44]:
np.exp(a)

array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05],
       [1.20260428e+06, 3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08]])

In [45]:
np.log10(a)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335],
       [1.14612804, 1.17609126, 1.20411998],
       [1.23044892, 1.25527251, 1.2787536 ]])

In [47]:
x = np.array([1,2,3])

In [48]:
y = x

In [49]:
y

array([1, 2, 3])

In [50]:
z = np.copy(x)

In [51]:
z

array([1, 2, 3])

In [52]:
x[0] = 100

In [53]:
y

array([100,   2,   3])

In [54]:
z

array([1, 2, 3])

In [55]:
id(z)

2123330476464

In [56]:
id(x)

2123330244208

In [57]:
id(y)

2123330244208

In [59]:
x

array([100,   2,   3])

In [60]:
id(x[0])

2123329578736

In [61]:
y

array([100,   2,   3])

In [62]:
id(y[0])

2123329576688

In [63]:
id(x[1])

2123329579408

In [64]:
id(y[1])

2123329578384

In [65]:
id(z[1])

2123329580880

In [66]:
x = np.array([1,2,3])

In [67]:
y = x

In [68]:
id(x)

2123330470704

In [69]:
id(y)

2123330470704

In [70]:
id(x[0])

2123329578928

In [71]:
id(y[0])

2123329577072

In [72]:
pr= np.array([567,345])

In [73]:
df = pr

In [74]:
id(pr)

2123330245360

In [75]:
id(df)

2123330245360

In [76]:
id(pr[0])

2123329577904

In [77]:
id(df[0])

2123329577648

In [78]:
id(pr[1])

2123329581328

In [79]:
id(df[1])

2123329577264

In [80]:
id(pr[1]) == id(df[0])

True

In [81]:
id(pr) == id(df)

True

In [83]:
ab = np.array([34,67,89])

In [84]:
id(ab[0]) == id(pr[0])

True

In [85]:
c = "monk"

In [86]:
id(c) == id(pr[0])

False